//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoJoin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoJoin.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select elements.
        /// </summary>
        public static string ErrorNoSelectedElements {
            get {
                return ResourceManager.GetString("ErrorNoSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select beams.
        /// </summary>
        public static string ErrorSelectBeams {
            get {
                return ResourceManager.GetString("ErrorSelectBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a single element.
        /// </summary>
        public static string ErrorSelectSingleElement {
            get {
                return ResourceManager.GetString("ErrorSelectSingleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All joins are already in the required priority..
        /// </summary>
        public static string MessageJoinPriorityNoJoin {
            get {
                return ResourceManager.GetString("MessageJoinPriorityNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements have no intersetions or already joined.
        /// </summary>
        public static string MessageNoIntersectionNoJoin {
            get {
                return ResourceManager.GetString("MessageNoIntersectionNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element has no intersections, the cut operation is cancelled.
        /// </summary>
        public static string MessageNoIntersectionsNoCut {
            get {
                return ResourceManager.GetString("MessageNoIntersectionsNoCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams processed.
        /// </summary>
        public static string ResultBeams1 {
            get {
                return ResourceManager.GetString("ResultBeams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors.
        /// </summary>
        public static string ResultBeams2 {
            get {
                return ResourceManager.GetString("ResultBeams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disjoin beam ends.
        /// </summary>
        public static string TransactionBeamUnjoin {
            get {
                return ResourceManager.GetString("TransactionBeamUnjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a cope.
        /// </summary>
        public static string TransactionCope {
            get {
                return ResourceManager.GetString("TransactionCope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut geometry.
        /// </summary>
        public static string TransactionCut {
            get {
                return ResourceManager.GetString("TransactionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join elements.
        /// </summary>
        public static string TransactionJoin {
            get {
                return ResourceManager.GetString("TransactionJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disjoin elements.
        /// </summary>
        public static string TransactionUnjoin {
            get {
                return ResourceManager.GetString("TransactionUnjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many elements are selected.
        /// </summary>
        public static string WarningTooManyElements1 {
            get {
                return ResourceManager.GetString("WarningTooManyElements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this may negatively affect at the model&apos;s performance. Continue.
        /// </summary>
        public static string WarningTooManyElements2 {
            get {
                return ResourceManager.GetString("WarningTooManyElements2", resourceCulture);
            }
        }
    }
}
