//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoJoin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoJoin.MyStrings - Copy", typeof(MyStrings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите элементы.
        /// </summary>
        public static string ErrorNoSelectedElements {
            get {
                return ResourceManager.GetString("ErrorNoSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите балки.
        /// </summary>
        public static string ErrorSelectBeams {
            get {
                return ResourceManager.GetString("ErrorSelectBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите только один элемент.
        /// </summary>
        public static string ErrorSelectSingleElement {
            get {
                return ResourceManager.GetString("ErrorSelectSingleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все соединения уже соответствуют заданному приоритету.
        /// </summary>
        public static string MessageJoinPriorityNoJoin {
            get {
                return ResourceManager.GetString("MessageJoinPriorityNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементы не имеют пересечений или уже соединены.
        /// </summary>
        public static string MessageNoIntersectionNoJoin {
            get {
                return ResourceManager.GetString("MessageNoIntersectionNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент не имеет пересечений. Вырезание не выполнено.
        /// </summary>
        public static string MessageNoIntersectionsNoCut {
            get {
                return ResourceManager.GetString("MessageNoIntersectionsNoCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработано балок.
        /// </summary>
        public static string ResultBeams1 {
            get {
                return ResourceManager.GetString("ResultBeams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ошибок.
        /// </summary>
        public static string ResultBeams2 {
            get {
                return ResourceManager.GetString("ResultBeams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена соединений балок.
        /// </summary>
        public static string TransactionBeamUnjoin {
            get {
                return ResourceManager.GetString("TransactionBeamUnjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание врезки.
        /// </summary>
        public static string TransactionCope {
            get {
                return ResourceManager.GetString("TransactionCope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезание геометрии.
        /// </summary>
        public static string TransactionCut {
            get {
                return ResourceManager.GetString("TransactionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение элементов.
        /// </summary>
        public static string TransactionJoin {
            get {
                return ResourceManager.GetString("TransactionJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсоединение элементов.
        /// </summary>
        public static string TransactionUnjoin {
            get {
                return ResourceManager.GetString("TransactionUnjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделено большое количество элементов.
        /// </summary>
        public static string WarningTooManyElements1 {
            get {
                return ResourceManager.GetString("WarningTooManyElements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to их соединение может привести к снижение быстродействия модели. Продолжить.
        /// </summary>
        public static string WarningTooManyElements2 {
            get {
                return ResourceManager.GetString("WarningTooManyElements2", resourceCulture);
            }
        }
    }
}
